/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;


/**
 *
 * @author Dell
 */
public class Competitor_table extends javax.swing.JFrame {

    /**
     * Creates new form Competitor_table
     */ 
    Connection con = null;
    String id_before_change ;
    int selected_row_before_chage;
    ArrayList<String[]> List = new ArrayList<String[]>(); // list for Combobox with Coachs
    public Competitor_table(String connectionUrl) {
        initComponents();
        try{
        con = DriverManager.getConnection(connectionUrl);
        }catch(Exception e)
        {
            
        }
        get_Coach g = new get_Coach(this,con,List);
        g.execute();
        CompetitorView show = new CompetitorView(con,CompetitorJTable);
        show.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CompetitorJTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Coach = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Surname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1_Sex = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        BirthDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        add_Competitor_Button = new javax.swing.JButton();
        Delete_Competitor_Button = new javax.swing.JButton();
        Accept_Button = new javax.swing.JButton();
        Clear_button = new javax.swing.JButton();
        Change_Competitor_Button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        idCompetitor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CompetitorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID","IDTrenera", "Imie", "Nazwisko", "Plec","Data_Urodzenia","E-mail","Trener","Kwota_stypendium"
            }
        ));
        jScrollPane1.setViewportView(CompetitorJTable);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Zawodnicy:");

        jLabel1.setText("ID zawodnika:");

        jLabel2.setText("Wybierz trenera:");

        jComboBox_Coach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel3.setText("Imię:");

        jLabel4.setText("Nazwisko:");

        jLabel5.setText("Płeć:");

        jComboBox1_Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kobieta", "Mezczyzna" }));
        jComboBox1_Sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_SexActionPerformed(evt);
            }
        });

        jLabel6.setText("Data urodzenia:");

        jLabel7.setText("E-mail:");

        add_Competitor_Button.setText("Dodaj nowego zawodnika");
        add_Competitor_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_Competitor_ButtonActionPerformed(evt);
            }
        });

        Delete_Competitor_Button.setText("Kasuj zawodnika");
        Delete_Competitor_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Competitor_ButtonActionPerformed(evt);
            }
        });

        Accept_Button.setText("Zatwierdź zmiany");
        Accept_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept_ButtonActionPerformed(evt);
            }
        });

        Clear_button.setText("Wyczyść");

        Change_Competitor_Button.setText("Zmień dane");
        Change_Competitor_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change_Competitor_ButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Wyświetl osiągnięcia i stypendia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(idCompetitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox1_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox_Coach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Change_Competitor_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(add_Competitor_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Delete_Competitor_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Accept_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCompetitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Coach, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Change_Competitor_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_Competitor_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Competitor_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Accept_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_SexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_SexActionPerformed

    private void add_Competitor_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_Competitor_ButtonActionPerformed
        // TODO add your handling code here:
      String BirthData = BirthDate.getText();
      StringBuilder b = new StringBuilder();
      if(BirthData.length() == 8)
      {
          for(int i = 0;i<8;i++)
          {
          
          b.append(BirthData.charAt(i));
          if(i == 3 || i == 5) b.append('-');
          }
      }else b.append(BirthData);
      String[] Coach = List.get(jComboBox_Coach.getSelectedIndex());
      
     
      String[] values = new String[]{idCompetitor.getText(),Coach[0],FirstName.getText(),Surname.getText(),String.valueOf(jComboBox1_Sex.getSelectedItem()),b.toString(),Email.getText(),Coach[1] + " "+Coach[2]};
   
      Competitor_Add a = new Competitor_Add(con,values,CompetitorJTable);
      a.execute();
    }//GEN-LAST:event_add_Competitor_ButtonActionPerformed

    private void Delete_Competitor_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Competitor_ButtonActionPerformed
        // TODO add your handling code here:
         Competitor_Delete d = new Competitor_Delete(con,CompetitorJTable);
         d.execute();
        
    }//GEN-LAST:event_Delete_Competitor_ButtonActionPerformed

    private void Change_Competitor_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change_Competitor_ButtonActionPerformed
        // TODO add your handling code here:
     idCompetitor.setText(CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),0).toString()); 
     id_before_change = CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),0).toString();
     selected_row_before_chage = CompetitorJTable.getSelectedRow();
     FirstName.setText(CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),2).toString());
     Surname.setText(CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),3).toString());
     int sex;
     String what = (CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),4).toString());
     if(what.length() == 7)
     {
         sex = 0;
     }
     else sex = 1;
     jComboBox1_Sex.setSelectedIndex(sex);
     BirthDate.setText(CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),5).toString());
     Email.setText(CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),6).toString());
     String List_Search = CompetitorJTable.getValueAt(CompetitorJTable.getSelectedRow(),1).toString();
     int index = 0;
     for(String[] I : List)
     {
         if(I[0].equals(List_Search) )
         {
             jComboBox_Coach.setSelectedIndex(index);
             break;
         }
         index++;
     }
     
     
    }//GEN-LAST:event_Change_Competitor_ButtonActionPerformed

    private void Accept_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept_ButtonActionPerformed
        // TODO add your handling code here:
         String BirthData = BirthDate.getText();
         StringBuilder b = new StringBuilder();
         if(BirthData.length() == 8)
         {
          for(int i = 0;i<8;i++)
          {
          
          b.append(BirthData.charAt(i));
          if(i == 3 || i == 5) b.append('-');
          }
      }else b.append(BirthData);
      String[] Coach = List.get(jComboBox_Coach.getSelectedIndex());
      String sex;
      if(jComboBox1_Sex.getSelectedIndex() == 0)
      {
        sex = "Kobieta";
      
      }
      else sex = "Mezczyzna";
      
      String[] values = new String[]{idCompetitor.getText(),Coach[0],FirstName.getText(),Surname.getText(),sex,b.toString(),Email.getText(),Coach[1] +" "+Coach[2]};
      
   
      Competitor_Change a = new Competitor_Change(con,values,CompetitorJTable,id_before_change,selected_row_before_chage);
      a.execute();
        
    }//GEN-LAST:event_Accept_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept_Button;
    private javax.swing.JTextField BirthDate;
    private javax.swing.JButton Change_Competitor_Button;
    private javax.swing.JButton Clear_button;
    private javax.swing.JTable CompetitorJTable;
    private javax.swing.JButton Delete_Competitor_Button;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField Surname;
    private javax.swing.JButton add_Competitor_Button;
    private javax.swing.JTextField idCompetitor;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1_Sex;
    public javax.swing.JComboBox<String> jComboBox_Coach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
